spring.application.name=school-management-system
server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/school_management
spring.datasource.username=school_management_ta
spring.datasource.password=P@ssw0rd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.schema=school_management

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations
spring.flyway.schema=school_management

#spring.jpa.show-sql=true
